# Generated by Django 4.2.6 on 2023-10-21 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllianceTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(choices=[('s1', 's1'), ('s2', 's2'), ('s3', 's3'), ('s4', 's4')], max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('server', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FourmizzzCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(choices=[('s1', 's1'), ('s2', 's2'), ('s3', 's3'), ('s4', 's4')], max_length=100, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('cookie_session', models.CharField(help_text="Grab the value from cookie PHPSESSID (<a target='_blank' rel='noopener' href='https://developer.chrome.com/docs/devtools/application/cookies/'>Click here</a>)", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(choices=[('s1', 's1'), ('s2', 's2'), ('s3', 's3'), ('s4', 's4')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('alliance', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.alliancetarget')),
            ],
            options={
                'unique_together': {('server', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RankingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('server', models.CharField(choices=[('s1', 's1'), ('s2', 's2'), ('s3', 's3'), ('s4', 's4')], editable=False, max_length=100)),
                ('player', models.CharField(editable=False, max_length=100)),
                ('hunting_field', models.PositiveBigIntegerField(editable=False)),
                ('trophies', models.IntegerField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='PrecisionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('hunting_field', models.PositiveBigIntegerField(editable=False)),
                ('trophies', models.IntegerField(editable=False)),
                ('processed', models.BooleanField(default=False)),
                ('player', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='scraper.playertarget')),
            ],
        ),
    ]
