# Generated by Django 4.2.6 on 2023-10-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fourmizzzcredentials',
            name='cookie_session',
            field=models.CharField(help_text="Grab the value from cookie PHPSESSID (<a target='_blank' rel='noopener' href='https://developer.chrome.com/docs/devtools/application/cookies/'>Click here</a>)", max_length=100),
        ),
    ]
