# Generated by Django 4.2.6 on 2023-10-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='precisionsnapshot',
            name='hunting_field_diff',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='precisionsnapshot',
            name='trophies_diff',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='rankingsnapshot',
            name='hunting_field_diff',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='rankingsnapshot',
            name='trophies_diff',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
