# Generated by Django 4.2.6 on 2023-10-21 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_precisionsnapshot_hunting_field_diff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precisionsnapshot',
            name='hunting_field_diff',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='precisionsnapshot',
            name='player',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to='scraper.playertarget'),
        ),
        migrations.AlterField(
            model_name='rankingsnapshot',
            name='hunting_field_diff',
            field=models.BigIntegerField(default=0, editable=False),
        ),
    ]
