# Generated by Django 4.2.6 on 2026-01-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0002_fourmizzzserver_n_scanned_pages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fourmizzzserver",
            name="username",
            field=models.CharField(
                help_text="This is not used. This is only for you to remember what account you picked the cookie from.",
                max_length=100,
            ),
        ),
    ]
