# Generated by Django 4.2.6 on 2023-10-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_alter_precisionsnapshot_hunting_field_diff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precisionsnapshot',
            name='player',
            field=models.ForeignKey(editable=False, on_delete=models.SET(None), to='scraper.playertarget'),
        ),
    ]
