# Generated by Django 4.2.6 on 2026-01-31 22:31

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0003_alter_fourmizzzserver_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="playertarget",
            name="mv",
            field=models.BooleanField(default=False),
        ),
    ]
