# Generated by Django 4.2.6 on 2023-10-21 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_alter_precisionsnapshot_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precisionsnapshot',
            name='player',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='scraper.playertarget'),
        ),
    ]
