# Generated by Django 4.2.6 on 2023-10-28 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraper', '0002_fourmizzzserver_n_scanned_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Captain Hook', max_length=100)),
                ('url', models.CharField(help_text="<a target='_blank' rel='noopener' href='https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks'>How to make a webhook</a>", max_length=200)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.fourmizzzserver')),
            ],
        ),
    ]
